# Generated by Django 2.2.1 on 2019-06-15 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_add',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Posted'),
        ),
    ]
