# Generated by Django 2.2.1 on 2019-06-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volai', '0002_auto_20190614_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_adress',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_pass',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
